# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agnix = {
    pname = "agnix";
    version = "v0.18.0";
    src = fetchFromGitHub {
      owner = "agent-sh";
      repo = "agnix";
      rev = "v0.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-R7luTBydtj8H8L/rRXYvWEy45Krg+lL9gTeJL4j/0uA=";
    };
  };
  any-buddy = {
    pname = "any-buddy";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "cpaczek";
      repo = "any-buddy";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-nkAeA2MuBmiDcBjIGzIbfxt0nvkHC++OSD+OWWwQ/e0=";
    };
  };
  claude-code = {
    pname = "claude-code";
    version = "2.1.100";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.1.100.tgz";
      sha256 = "sha256-Dkip2mnbcvks8SbZVBqXajaRi1SQEemN2IDiHxlaqbA=";
    };
  };
  context7-mcp = {
    pname = "context7-mcp";
    version = "2.1.7";
    src = fetchurl {
      url = "https://github.com/upstash/context7/archive/refs/tags/@upstash/context7-mcp@2.1.7.tar.gz";
      name = "context7--upstash-context7-mcp_2.1.7.tar.gz";
      sha256 = "sha256-0l42zdVNiyAQei9Fl29xNLBl74u74UA4zf7jZzsB7ME=";
    };
  };
  effect-mcp = {
    pname = "effect-mcp";
    version = "v0.1.16";
    src = fetchFromGitHub {
      owner = "tim-smart";
      repo = "effect-mcp";
      rev = "v0.1.16";
      fetchSubmodules = false;
      sha256 = "sha256-KRE/5TzAoghBayNrnKtocYHE/vmFQraZfkS7CKN2E5c=";
    };
  };
  git-absorb = {
    pname = "git-absorb";
    version = "0.9.0";
    src = fetchFromGitHub {
      owner = "tummychow";
      repo = "git-absorb";
      rev = "0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-jAR+Vq6SZZXkseOxZVJSjsQOStIip8ThiaLroaJcIfc=";
    };
  };
  git-branchless = {
    pname = "git-branchless";
    version = "v0.10.0";
    src = fetchFromGitHub {
      owner = "arxanas";
      repo = "git-branchless";
      rev = "v0.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-8uv+sZRr06K42hmxgjrKk6FDEngUhN/9epixRYKwE3U=";
    };
  };
  git-intel-mcp = {
    pname = "git-intel-mcp";
    version = "9f216bab8d6bc3a3b850ad77f27d02d63a71e10d";
    src = fetchgit {
      url = "https://github.com/hoangsonww/GitIntel-MCP-Server.git";
      rev = "9f216bab8d6bc3a3b850ad77f27d02d63a71e10d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UCIUmU6slN9EjL8Bf2JKfvyoVKE0jgUsfLd8OocdwNc=";
    };
    date = "2026-03-18";
  };
  git-revise = {
    pname = "git-revise";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "mystor";
      repo = "git-revise";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-OdkhYEq30RtDOeCQWl/L9FMgCttznzihbYgT8B6KYuY=";
    };
  };
  github-copilot-cli = {
    pname = "github-copilot-cli";
    version = "1.0.22";
    src = fetchurl {
      url = "https://github.com/github/copilot-cli/releases/download/v1.0.22/copilot-linux-x64.tar.gz";
      sha256 = "sha256-2h40sQXtHPpftSz0MQg98PVW078PLMyPmZ+wwAMxQIE=";
    };
  };
  github-mcp-server = {
    pname = "github-mcp-server";
    version = "v0.32.0";
    src = fetchFromGitHub {
      owner = "github";
      repo = "github-mcp-server";
      rev = "v0.32.0";
      fetchSubmodules = false;
      sha256 = "sha256-BD/t3UBAvrzJpRI7b06FjE8c+vzdQiXsj6eiUGQX6uA=";
    };
  };
  kagiapi = {
    pname = "kagiapi";
    version = "0.2.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/k/kagiapi/kagiapi-0.2.1.tar.gz";
      sha256 = "sha256-NV/kB7TGg9bwhIJ+T4VP2VE03yhC8V0Inaz/Yg4/Sus=";
    };
  };
  kagimcp = {
    pname = "kagimcp";
    version = "933e3384e9b1f34ebcc84b85310be7a6548900db";
    src = fetchFromGitHub {
      owner = "kagisearch";
      repo = "kagimcp";
      rev = "933e3384e9b1f34ebcc84b85310be7a6548900db";
      fetchSubmodules = false;
      sha256 = "sha256-jTxmn6H0SPV/vwDW+4tQiTXceVJZwwVgLXsF9bjSPS8=";
    };
    date = "2026-04-08";
  };
  kiro-cli = {
    pname = "kiro-cli";
    version = "1.29.6";
    src = fetchurl {
      url = "https://desktop-release.q.us-east-1.amazonaws.com/1.29.6/kirocli-x86_64-linux.tar.gz";
      sha256 = "sha256-6FZgHdKBDz8zrrJf0MgGtzKz279j4X3H/B6tW+0WlZ8=";
    };
  };
  kiro-cli-darwin = {
    pname = "kiro-cli-darwin";
    version = "1.29.6";
    src = fetchurl {
      url = "https://desktop-release.q.us-east-1.amazonaws.com/1.29.6/Kiro%20CLI.dmg";
      name = "kiro-cli.dmg";
      sha256 = "sha256-qe9svpw3ngk9EU12woeMXW8+gTNYxGfzdePVUgodUWY=";
    };
  };
  kiro-gateway = {
    pname = "kiro-gateway";
    version = "e6f23c22fc5e9aa7a22e4c31af56cdc6f859afbd";
    src = fetchgit {
      url = "https://github.com/jwadow/kiro-gateway.git";
      rev = "e6f23c22fc5e9aa7a22e4c31af56cdc6f859afbd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-V9sS82Jwx5y03ojNueHr+0qfp87fkACrdr7iP78Yxeo=";
    };
    date = "2026-02-12";
  };
  mcp-language-server = {
    pname = "mcp-language-server";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "isaacphi";
      repo = "mcp-language-server";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-T0wuPSShJqVW+CcQHQuZnh3JOwqUxAKv1OCHwZMr7KM=";
    };
  };
  mcp-proxy = {
    pname = "mcp-proxy";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "sparfenyuk";
      repo = "mcp-proxy";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-oSRchkCnPoQ3KZXPW49O2yTgNRi9aJbKki3z9BxBPhA=";
    };
  };
  modelcontextprotocol-servers = {
    pname = "modelcontextprotocol-servers";
    version = "f4244583a6af9425633e433a3eec000d23f4e011";
    src = fetchFromGitHub {
      owner = "modelcontextprotocol";
      repo = "servers";
      rev = "f4244583a6af9425633e433a3eec000d23f4e011";
      fetchSubmodules = false;
      sha256 = "sha256-bHknioQu8i5RcFlBBdXUQjsV4WN1IScnwohGRxXgGDk=";
    };
    date = "2026-03-17";
  };
  openmemory-mcp = {
    pname = "openmemory-mcp";
    version = "a65c920636b1b39618e833f1a0f8494aebccafcd";
    src = fetchFromGitHub {
      owner = "CaviraOSS";
      repo = "OpenMemory";
      rev = "a65c920636b1b39618e833f1a0f8494aebccafcd";
      fetchSubmodules = false;
      sha256 = "sha256-cXbftztatmbYPv4uYh3YVpXS65yHzs+D6EOR5Y7x9rw=";
    };
    date = "2026-04-08";
  };
  sympy-mcp = {
    pname = "sympy-mcp";
    version = "646c69558b622ab0e2814c58aa82143e56b76c33";
    src = fetchFromGitHub {
      owner = "sdiehl";
      repo = "sympy-mcp";
      rev = "646c69558b622ab0e2814c58aa82143e56b76c33";
      fetchSubmodules = false;
      sha256 = "sha256-AjRdiBtsF/ZpAUt+TPhvkT8VQ3y7rcJSogSSyQQXytI=";
    };
    date = "2026-03-18";
  };
}
