# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  agnix = {
    pname = "agnix";
    version = "v0.18.0";
    src = fetchFromGitHub {
      owner = "agent-sh";
      repo = "agnix";
      rev = "v0.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-R7luTBydtj8H8L/rRXYvWEy45Krg+lL9gTeJL4j/0uA=";
    };
  };
  git-absorb = {
    pname = "git-absorb";
    version = "0.9.0";
    src = fetchFromGitHub {
      owner = "tummychow";
      repo = "git-absorb";
      rev = "0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-jAR+Vq6SZZXkseOxZVJSjsQOStIip8ThiaLroaJcIfc=";
    };
  };
  git-branchless = {
    pname = "git-branchless";
    version = "v0.10.0";
    src = fetchFromGitHub {
      owner = "arxanas";
      repo = "git-branchless";
      rev = "v0.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-8uv+sZRr06K42hmxgjrKk6FDEngUhN/9epixRYKwE3U=";
    };
  };
  git-revise = {
    pname = "git-revise";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "mystor";
      repo = "git-revise";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-OdkhYEq30RtDOeCQWl/L9FMgCttznzihbYgT8B6KYuY=";
    };
  };
}
