# DNS root hints — the IANA root name server list served by InterNIC,
# installed as `$out/root.hints` for a resolver's `hint` zone (unbound's
# `root-hints`, BIND's `type hint`).
#
# Unlike every other sourced package here, the URL is VERSION-INDEPENDENT:
# there is one canonical path and it is re-served whenever the root zone
# changes. The "version" is the root-zone serial stamped inside the file
# body itself, which is why the version check greps the fetched content
# rather than a tag or a release redirect, and why the URL template
# ignores its `ver` argument. `mkUpdateScript`'s per-platform mapping
# collapses to the single `src` key for the same reason — the artifact is
# platform-independent. It is also the only consumer of
# `mkUpdateScript`'s `alwaysPrefetch` mode; see the note beside that
# argument below for why a version-independent URL cannot rely on the
# version-equality early exit.
#
# Supporting package; its public role is encoded by the native recipe tree.
# earmarked repo split can lift the subtree whole.
{
  pkgs,
  packageLib,
  repoPath,
  ...
}: let
  inherit (pkgs) fetchurl lib;
  vu = packageLib;

  sources = builtins.fromJSON (builtins.readFile ../../../../sources.json);

  url = "https://www.internic.net/domain/named.root";
in
  pkgs.stdenvNoCC.mkDerivation {
    pname = "dns-root-hints";
    inherit (sources) version;
    # fetchurl of a single flat file, so the recorded hash is the FILE's
    # — no --unpack on the prefetch below, unlike the fetchzip packages
    # in this directory.
    #
    # Split on purpose: the URL comes from the `let` binding, only the
    # hash from the sidecar. The sidecar is GENERATED by the
    # updateScript below, out of `platforms` — which is itself built
    # from that binding — so reading the URL back out of it would close
    # a loop and let a hand-edit re-point what the update script
    # fetches. The hash is the half that genuinely varies with upstream
    # content and can only be learned by prefetching, so it is the only
    # half worth reading back.
    src = fetchurl {
      inherit url;
      inherit (sources.src) hash;
    };

    # `src` is a bare file, so there is nothing to unpack and no source
    # tree to configure or build. Expressed with the `dont*` flags rather
    # than the legacy `phases` list, which suppresses the runHook
    # plumbing along with the phases.
    dontUnpack = true;
    dontConfigure = true;
    dontBuild = true;

    installPhase = ''
      runHook preInstall
      mkdir -p "$out"
      cp "$src" "$out/root.hints"
      runHook postInstall
    '';

    passthru.updateScript = vu.mkUpdateScript {
      inherit pkgs;
      pname = "dns-root-hints";
      sourcesFile = repoPath ../../../../sources.json;
      platforms = {
        # One platform-independent artifact, and the URL carries no
        # version — hence the ignored `ver` argument.
        src = _: url;
      };
      # THIS is what guarantees hash freshness, not the version check
      # below. `mkUpdateScript`'s default flow early-exits when the
      # reported version equals the recorded one, so for a
      # version-independent URL the version string would be the sole
      # change signal: upstream re-serving modified content without
      # advancing the serial would leave the committed hash stale and
      # fetchurl failing until the serial happened to move. With
      # alwaysPrefetch the file is fetched and hashed every sweep and the
      # sidecar comparison decides whether to write, so no version
      # capture — however careful — is load-bearing for correctness any
      # more. Costs one ~3 KB fetch 4x/day.
      alwaysPrefetch = true;
      # Absolute store paths: this string is interpolated into a
      # writeShellScript wrapper, which the update pipeline invokes
      # directly and which therefore cannot assume a PATH.
      #
      # The serial is retained as the HUMAN-FACING version — it names the
      # root-zone revision in the store path and in the update PR — so it
      # still has to be captured correctly. It is YYYYMMDD followed by a
      # two-digit within-day revision counter, not a bare date. Capturing
      # it with a fixed digit count (this was `[0-9]{8}`) truncated it to
      # the date, so a same-day bump `…01` -> `…02` read as no change at
      # all. Under alwaysPrefetch that no longer strands the hash — the
      # prefetch runs regardless and the write is decided by comparison —
      # but it would still mislabel the derivation. Hence `+` rather than
      # `{10}`: anchoring on a digit count is exactly what broke, and the
      # literal `version of root zone:` prefix already bounds the match.
      versionCheck.cmd = "${pkgs.curl}/bin/curl -fsSL ${url} | ${pkgs.gnugrep}/bin/grep -oP 'version of root zone:\\s+\\K[0-9]+' | ${pkgs.coreutils}/bin/head -1";
    };

    meta = {
      description = "IANA DNS root name server hints (named.root)";
      homepage = "https://www.internic.net/domain/named.root";
      license = lib.licenses.publicDomain;
      platforms = lib.platforms.all;
    };
  }
