# Generated by nvfetcher. Do not edit manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  github-copilot-cli = {
    pname = "github-copilot-cli";
    version = "1.0.18";
    src = fetchurl {
      url = "https://github.com/github/copilot-cli/releases/download/v1.0.18/copilot-linux-x64.tar.gz";
      sha256 = "sha256-fso7uwOj20/vklD4gFLMxaowypX65xrdcOHmb8sDeRM=";
    };
  };
  kiro-cli = {
    pname = "kiro-cli";
    version = "1.29.3";
    src = fetchurl {
      url = "https://desktop-release.q.us-east-1.amazonaws.com/1.29.3/kirocli-x86_64-linux.tar.gz";
      sha256 = "sha256-DD3eQ9lpV+M0d40AxnLP6dOw/fvdeuAcPWwpUMonuNk=";
    };
  };
  kiro-gateway = {
    pname = "kiro-gateway";
    version = "e6f23c22fc5e9aa7a22e4c31af56cdc6f859afbd";
    src = fetchgit {
      url = "https://github.com/jwadow/kiro-gateway.git";
      rev = "e6f23c22fc5e9aa7a22e4c31af56cdc6f859afbd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-V9sS82Jwx5y03ojNueHr+0qfp87fkACrdr7iP78Yxeo=";
    };
    date = "2026-02-12";
  };
}
