# Customizes a Semble Python package with extra grammars, path mappings and
# content-routed embedding models. `spec` is the shape `customization.nix`
# documents. Each customization patches only when it is not vanilla; with
# both vanilla the package is returned unchanged.
{
  lib,
  pkgs,
}: package: requested: let
  customization = import ./customization.nix {inherit lib;};
  spec = customization.normalize requested;
  errors = customization.errors spec;
  grammarsVanilla = customization.grammarsVanilla spec;
  modelsVanilla = customization.modelsVanilla spec;
  grammarLanguages = map (grammar: grammar.language) spec.grammars;
  mappings = customization.mappingList spec.pathMappings;
  grammarEntries =
    map
    (grammar: {
      inherit (grammar) language;
      parser = "${grammar}/parser";
      symbol = "tree_sitter_${lib.replaceStrings ["-"] ["_"] grammar.language}";
    })
    spec.grammars;
  customizationFingerprint = builtins.hashString "sha256" (builtins.toJSON {
    inherit grammarEntries mappings;
  });
  grammarLoader = pkgs.writeText "semble-extra-grammars.py" ''
    # cspell:ignore argtypes pythonapi restype
    from __future__ import annotations

    import ctypes
    from functools import cache

    from semble_grammars import GrammarLoadError, LanguageNotFoundError
    from tree_sitter import Language, Parser

    _GRAMMARS = ${builtins.toJSON (lib.listToAttrs (map (entry: lib.nameValuePair entry.language entry) grammarEntries))}
    _LOADED_LIBRARIES: dict[str, ctypes.CDLL] = {}


    def _load_capsule(path: str, symbol: str) -> object:
        try:
            library = ctypes.CDLL(path)
        except OSError as exc:
            raise GrammarLoadError(f"Failed to load extra grammar {path!r}") from exc
        _LOADED_LIBRARIES[path] = library

        try:
            entry_point = getattr(library, symbol)
        except AttributeError as exc:
            raise GrammarLoadError(f"{path!r}: missing expected symbol {symbol!r}") from exc

        entry_point.restype = ctypes.c_void_p
        language_pointer = entry_point()
        if not language_pointer:
            raise GrammarLoadError(f"{path!r}: {symbol}() returned a null language pointer")

        py_capsule_new = ctypes.pythonapi.PyCapsule_New
        py_capsule_new.restype = ctypes.py_object
        py_capsule_new.argtypes = (ctypes.c_void_p, ctypes.c_char_p, ctypes.c_void_p)
        return py_capsule_new(language_pointer, b"tree_sitter.Language", None)


    @cache
    def get_parser(name: str) -> Parser:
        entry = _GRAMMARS.get(name)
        if entry is None:
            raise LanguageNotFoundError(f"Unknown extra language {name!r}")
        capsule = _load_capsule(entry["parser"], entry["symbol"])
        return Parser(Language(capsule))
  '';
  modelTable = pkgs.writeText "semble-models.py" ''
    """Embedding-model routing table, generated by Nix: content set -> model."""

    from __future__ import annotations

    import json

    _TABLE = json.loads(${builtins.toJSON (builtins.toJSON (customization.table spec))})
    DEFAULT_CONTENT: list[str] = _TABLE["DEFAULT_CONTENT"]
    DEFAULT_MODEL: str | None = _TABLE["DEFAULT_MODEL"]
    MODELS: list[dict] = _TABLE["MODELS"]
  '';
  pathMappingLoader = pkgs.writeText "semble-path-mappings.py" ''
    from __future__ import annotations

    import json
    from fnmatch import fnmatchcase
    from pathlib import Path
    from typing import Any

    CUSTOMIZATION_FINGERPRINT = "${customizationFingerprint}"
    # In match order; the first matching pattern wins. A None language means
    # line chunking, with no parser lookup.
    _MAPPINGS: list[dict[str, Any]] = json.loads(${builtins.toJSON (builtins.toJSON mappings)})


    def find_mapping(file_path: Path, root: Path | None = None) -> dict[str, Any] | None:
        try:
            relative = file_path.relative_to(root).as_posix() if root is not None else file_path.as_posix()
        except ValueError:
            relative = file_path.as_posix()

        for mapping in _MAPPINGS:
            pattern = mapping["pattern"]
            candidate = relative if "/" in pattern else file_path.name
            if fnmatchcase(candidate, pattern):
                return mapping
        return None


    def get_mapped_content(file_path: Path, root: Path) -> str | None:
        mapping = find_mapping(file_path, root)
        return None if mapping is None else mapping["content"]
  '';
in
  if grammarsVanilla && modelsVanilla
  then package
  else
    assert lib.assertMsg (package ? overridePythonAttrs)
    "semble.customizePackage requires a Python package exposing overridePythonAttrs";
    assert lib.assertMsg (errors == [])
    "semble.customizePackage:\n${lib.concatStringsSep "\n" errors}";
      (package.overridePythonAttrs (old: {
        # The models patch applies on its own or on top of the grammar patch.
        patches =
          (old.patches or [])
          ++ lib.optional (!grammarsVanilla) ../patches/extra-grammars.patch
          ++ lib.optional (!modelsVanilla) ../patches/models.patch;
        postPatch =
          (old.postPatch or "")
          + lib.optionalString (!grammarsVanilla) ''
            ${pkgs.coreutils}/bin/cp ${grammarLoader} src/semble/extra_grammars.py
            ${pkgs.coreutils}/bin/cp ${pathMappingLoader} src/semble/path_mappings.py
          ''
          + lib.optionalString (!modelsVanilla) ''
            ${pkgs.coreutils}/bin/cp ${modelTable} src/semble/semble_models.py
          '';
      }))
      // {
        # `overridePythonAttrs` sees the derivation before a caller or overlay
        # extends it as a plain attrset. Merge from the public package value so
        # metadata such as updateFlakeInput survives the customization.
        passthru =
          (package.passthru or {})
          // {
            sembleExtraGrammarLanguages = grammarLanguages;
            sembleModels = customization.table spec;
            semblePathMappings = mappings;
          };
      }
