# Generated by checks/ai-delivery/generate.nix; do not edit.
{
  rows = [
    {
      ecosystem = "claude";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "agents";
      target = "$DEVENV_ROOT/.claude/agents/<name>.md";
      writerAttr = [
        "files"
        ".claude/agents/probe.md"
      ];
    }
    {
      ecosystem = "codex";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "agents";
      target = "$DEVENV_ROOT/.codex/agents/<name>.toml";
      writerAttr = [
        "files"
        ".codex/agents/probe.toml"
      ];
    }
    {
      ecosystem = "codex";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "agents";
      target = "$HOME/.codex/agents/<name>.toml";
      writerAttr = [
        "home"
        "file"
        ".codex/agents/probe.toml"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "agents";
      target = "$DEVENV_ROOT/.github/agents/<name>.agent.md";
      writerAttr = [
        "files"
        ".github/agents/probe.agent.md"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "agents";
      target = "$HOME/.copilot/agents/<name>.md";
      writerAttr = [
        "home"
        "file"
        ".copilot/agents/probe.md"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "devenv";
      primitive = "ownPathManaged";
      pruneTrigger = "On shell entry, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
      surface = "agents";
      target = "$DEVENV_ROOT/.kimchi/agents/<name>.md";
      writerAttr = [
        "tasks"
        "ai:kimchi:agents"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownPathManaged";
          pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$HOME/.config/kimchi/harness/agents/<name>.md";
          writerAttr = [
            "home"
            "activation"
            "kimchiAgentsPrune"
          ];
        }
      ];
      ecosystem = "kimchi";
      mode = "hm";
      primitive = "ownPathManaged";
      pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
      surface = "agents";
      target = "$HOME/.config/kimchi/harness/agents/<name>.md";
      writerAttr = [
        "home"
        "activation"
        "kimchiAgents"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "agents";
      target = "$DEVENV_ROOT/.kiro/agents/<name>.json";
      writerAttr = [
        "files"
        ".kiro/agents/probe.json"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "agents";
      target = "$HOME/.kiro/agents/<name>.json";
      writerAttr = [
        "home"
        "file"
        ".kiro/agents/probe.json"
      ];
    }
    {
      ecosystem = "claude";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "context";
      target = "$DEVENV_ROOT/.claude/CLAUDE.md";
      writerAttr = [
        "files"
        ".claude/CLAUDE.md"
      ];
    }
    {
      ecosystem = "claude";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "context";
      target = "$HOME/.claude/CLAUDE.md";
      writerAttr = [
        "home"
        "file"
        ".claude/CLAUDE.md"
      ];
    }
    {
      ecosystem = "codex";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "context";
      target = "$DEVENV_ROOT/AGENTS.md";
      writerAttr = [
        "files"
        "AGENTS.md"
      ];
    }
    {
      ecosystem = "codex";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "context";
      target = "$HOME/.codex/AGENTS.md";
      writerAttr = [
        "home"
        "file"
        ".codex/AGENTS.md"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "context";
      target = "$DEVENV_ROOT/.github/copilot-instructions.md";
      writerAttr = [
        "files"
        ".github/copilot-instructions.md"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "context";
      target = "$DEVENV_ROOT/AGENTS.md";
      writerAttr = [
        "files"
        "AGENTS.md"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "context";
      target = "$HOME/.config/kimchi/harness/AGENTS.md";
      writerAttr = [
        "home"
        "file"
        ".config/kimchi/harness/AGENTS.md"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownPathManaged";
          pruneTrigger = "On shell entry, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$DEVENV_ROOT/.kiro/steering/<legacy-owned-file>";
          writerAttr = [
            "tasks"
            "ai:kiro:retire-steering-copies"
          ];
        }
      ];
      ecosystem = "kiro";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "context";
      target = "$DEVENV_ROOT/AGENTS.md";
      writerAttr = [
        "files"
        "AGENTS.md"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownPathManaged";
          pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$HOME/.kiro/steering/<legacy-owned-file>";
          writerAttr = [
            "home"
            "activation"
            "retire-materialize-kiro-steering"
          ];
        }
        {
          primitive = "ownPathManaged";
          pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$HOME/.kiro/steering/<legacy-owned-file>";
          writerAttr = [
            "home"
            "activation"
            "retire-materialize-kiro-steering-ledger"
          ];
        }
      ];
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "context";
      target = "$HOME/.kiro/steering/AGENTS.md";
      writerAttr = [
        "home"
        "file"
        ".kiro/steering/AGENTS.md"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownPathDeclarative";
          pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
          target = "$DEVENV_ROOT/.claude/hooks/<name>";
          writerAttr = [
            "files"
            ".claude/hooks/probe"
          ];
        }
      ];
      ecosystem = "claude";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "hooks";
      target = "$DEVENV_ROOT/.claude/settings.json";
      writerAttr = [
        "files"
        ".claude/settings.json"
      ];
    }
    {
      ecosystem = "codex";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "hooks";
      target = "$DEVENV_ROOT/.codex/hooks.json";
      writerAttr = [
        "files"
        ".codex/hooks.json"
      ];
    }
    {
      ecosystem = "codex";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "hooks";
      target = "$HOME/.codex/hooks.json";
      writerAttr = [
        "home"
        "file"
        ".codex/hooks.json"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "hooks";
      target = "$DEVENV_ROOT/.kimchi/hooks.json";
      writerAttr = [
        "files"
        ".kimchi/hooks.json"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "devenv";
      primitive = "ownPathManaged";
      pruneTrigger = "On shell entry, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
      surface = "hooks";
      target = "$DEVENV_ROOT/.kiro/hooks/<name>.json";
      writerAttr = [
        "tasks"
        "ai:kiro:materialize-hooks"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownPathManaged";
          pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$HOME/.kiro/hooks/<name>.json";
          writerAttr = [
            "home"
            "activation"
            "materialize-kiro-hooks-prune"
          ];
        }
      ];
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownPathManaged";
      pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
      surface = "hooks";
      target = "$HOME/.kiro/hooks/<name>.json";
      writerAttr = [
        "home"
        "activation"
        "materialize-kiro-hooks-write"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "lspServers";
      target = "$DEVENV_ROOT/.github/lsp.json";
      writerAttr = [
        "files"
        ".github/lsp.json"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "lspServers";
      target = "$HOME/.copilot/lsp-config.json";
      writerAttr = [
        "home"
        "file"
        ".copilot/lsp-config.json"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "lspServers";
      target = "$DEVENV_ROOT/.kiro/settings/lsp.json";
      writerAttr = [
        "files"
        ".kiro/settings/lsp.json"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "lspServers";
      target = "$HOME/.kiro/settings/lsp.json";
      writerAttr = [
        "home"
        "file"
        ".kiro/settings/lsp.json"
      ];
    }
    {
      ecosystem = "codex";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "mcpServers";
      target = "$DEVENV_ROOT/.codex/config.toml";
      writerAttr = [
        "files"
        ".codex/config.toml"
      ];
    }
    {
      ecosystem = "codex";
      mode = "hm";
      primitive = "ownLeaves";
      pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "mcpServers";
      target = "$HOME/.codex/config.toml";
      writerAttr = [
        "home"
        "activation"
        "codexSettingsReconcile"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "mcpServers";
      target = "$DEVENV_ROOT/.config/github-copilot/mcp-config.json";
      writerAttr = [
        "files"
        ".config/github-copilot/mcp-config.json"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "mcpServers";
      target = "$HOME/.copilot/mcp-config.json";
      writerAttr = [
        "home"
        "file"
        ".copilot/mcp-config.json"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "devenv";
      primitive = "ownLeaves";
      pruneTrigger = "On shell entry, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "mcpServers";
      target = "$DEVENV_ROOT/.kimchi/mcp.json";
      writerAttr = [
        "tasks"
        "ai:kimchi:mcp-merge"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "hm";
      primitive = "ownLeaves";
      pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "mcpServers";
      target = "$HOME/.config/kimchi/harness/mcp.json";
      writerAttr = [
        "home"
        "activation"
        "kimchiMcpMerge"
      ];
    }
    {
      additionalWriters = [
        {
          condition = "ai.kiro.mcpWriteMode = \"merge\"";
          primitive = "ownLeaves";
          pruneTrigger = "On shell entry, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
          target = "$DEVENV_ROOT/.kiro/settings/mcp.json";
          writerAttr = [
            "tasks"
            "ai:kiro:materialize-mcp"
          ];
        }
      ];
      condition = "ai.kiro.mcpWriteMode = \"overwrite\" (default)";
      ecosystem = "kiro";
      mode = "devenv";
      primitive = "ownPathManaged";
      pruneTrigger = "On shell entry, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
      surface = "mcpServers";
      target = "$DEVENV_ROOT/.kiro/settings/mcp.json";
      writerAttr = [
        "tasks"
        "ai:kiro:materialize-mcp"
      ];
    }
    {
      additionalWriters = [
        {
          condition = "ai.kiro.mcpWriteMode = \"merge\"";
          primitive = "ownLeaves";
          pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
          target = "$HOME/.kiro/settings/mcp.json";
          writerAttr = [
            "home"
            "activation"
            "kiroMcpJson"
          ];
        }
        {
          condition = "ai.kiro.mcpWriteMode = \"overwrite\" (default)";
          primitive = "ownPathManaged";
          pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$HOME/.kiro/settings/mcp.json";
          writerAttr = [
            "home"
            "activation"
            "materialize-kiro-settings-prune"
          ];
        }
        {
          condition = "ai.kiro.mcpWriteMode = \"merge\"";
          primitive = "ownLeaves";
          pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
          target = "$HOME/.kiro/settings/mcp.json";
          writerAttr = [
            "home"
            "activation"
            "materialize-kiro-settings-prune"
          ];
        }
      ];
      condition = "ai.kiro.mcpWriteMode = \"overwrite\" (default)";
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownPathManaged";
      pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
      surface = "mcpServers";
      target = "$HOME/.kiro/settings/mcp.json";
      writerAttr = [
        "home"
        "activation"
        "kiroMcpJson"
      ];
    }
    {
      ecosystem = "claude";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "permissions";
      target = "$DEVENV_ROOT/.claude/settings.json";
      writerAttr = [
        "files"
        ".claude/settings.json"
      ];
    }
    {
      ecosystem = "codex";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "permissions";
      target = "$DEVENV_ROOT/.codex/config.toml";
      writerAttr = [
        "files"
        ".codex/config.toml"
      ];
    }
    {
      ecosystem = "codex";
      mode = "hm";
      primitive = "ownLeaves";
      pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "permissions";
      target = "$HOME/.codex/config.toml";
      writerAttr = [
        "home"
        "activation"
        "codexSettingsReconcile"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "devenv";
      primitive = "ownLeaves";
      pruneTrigger = "On shell entry, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "permissions";
      target = "$DEVENV_ROOT/.kimchi/permissions.json";
      writerAttr = [
        "tasks"
        "ai:kimchi:permissions-merge"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "hm";
      primitive = "ownLeaves";
      pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "permissions";
      target = "$HOME/.config/kimchi/harness/permissions.json";
      writerAttr = [
        "home"
        "activation"
        "kimchiPermissionsMerge"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "permissions";
      target = "$HOME/.kiro/settings/permissions.yaml";
      writerAttr = [
        "home"
        "file"
        ".kiro/settings/permissions.yaml"
      ];
    }
    {
      ecosystem = "claude";
      mode = "devenv";
      primitive = "ownPathManaged";
      pruneTrigger = "On shell entry, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
      surface = "rules";
      target = "$DEVENV_ROOT/.claude/rules/<name>.md";
      writerAttr = [
        "tasks"
        "ai:claude:materialize-rules"
      ];
    }
    {
      ecosystem = "claude";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "rules";
      target = "$HOME/.claude/rules/<name>.md";
      writerAttr = [
        "home"
        "file"
        ".claude/rules/probe.md"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownPathManaged";
          pruneTrigger = "On shell entry, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$DEVENV_ROOT/.codex/rules/<name>.rules";
          writerAttr = [
            "tasks"
            "ai:codex:materialize-execpolicy"
          ];
        }
      ];
      ecosystem = "codex";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "rules";
      target = "$DEVENV_ROOT/AGENTS.md";
      writerAttr = [
        "files"
        "AGENTS.md"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownPathManaged";
          pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$HOME/.codex/rules/<name>.rules";
          writerAttr = [
            "home"
            "activation"
            "materialize-codex-execpolicy-write"
          ];
        }
        {
          primitive = "ownPathManaged";
          pruneTrigger = "On activation, lib/ai/own.py removes every file the prior generation's ledger recorded and this one no longer declares, then rewrites the ledger; a file in the same directory that it never wrote is left alone. The arms are `DirContainer.remove` against that program's REMOVE_ARMS table, transcribed from the shell it replaced.";
          target = "$HOME/.codex/rules/<name>.rules";
          writerAttr = [
            "home"
            "activation"
            "materialize-codex-execpolicy-prune"
          ];
        }
      ];
      ecosystem = "codex";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "rules";
      target = "$HOME/.codex/AGENTS.md";
      writerAttr = [
        "home"
        "file"
        ".codex/AGENTS.md"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "rules";
      target = "$DEVENV_ROOT/.github/instructions/<name>.instructions.md";
      writerAttr = [
        "files"
        ".github/instructions/probe.instructions.md"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownPathDeclarative";
          pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
          target = "$DEVENV_ROOT/.kiro/steering/<name>.md";
          writerAttr = [
            "files"
            ".kiro/steering/scoped.md"
          ];
        }
      ];
      ecosystem = "kiro";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "rules";
      target = "$DEVENV_ROOT/AGENTS.md";
      writerAttr = [
        "files"
        "AGENTS.md"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "rules";
      target = "$HOME/.kiro/steering/<name>.md";
      writerAttr = [
        "home"
        "file"
        ".kiro/steering/probe.md"
      ];
    }
    {
      ecosystem = "claude";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "settings";
      target = "$DEVENV_ROOT/.claude/settings.json";
      writerAttr = [
        "files"
        ".claude/settings.json"
      ];
    }
    {
      ecosystem = "codex";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "settings";
      target = "$DEVENV_ROOT/.codex/config.toml";
      writerAttr = [
        "files"
        ".codex/config.toml"
      ];
    }
    {
      ecosystem = "codex";
      mode = "hm";
      primitive = "ownLeaves";
      pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "settings";
      target = "$HOME/.codex/config.toml";
      writerAttr = [
        "home"
        "activation"
        "codexSettingsReconcile"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "settings";
      target = "$DEVENV_ROOT/.config/github-copilot/settings.json";
      writerAttr = [
        "files"
        ".config/github-copilot/settings.json"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "hm";
      primitive = "ownLeaves";
      pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "settings";
      target = "$HOME/.copilot/settings.json";
      writerAttr = [
        "home"
        "activation"
        "copilotSettingsMerge"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownLeaves";
          pruneTrigger = "On shell entry, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
          target = "$DEVENV_ROOT/.config/kimchi/harness/settings.json";
          writerAttr = [
            "tasks"
            "ai:kimchi:harness-settings-merge"
          ];
        }
      ];
      ecosystem = "kimchi";
      mode = "devenv";
      primitive = "ownLeaves";
      pruneTrigger = "On shell entry, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "settings";
      target = "$DEVENV_ROOT/.kimchi/config.json";
      writerAttr = [
        "tasks"
        "ai:kimchi:config-merge"
      ];
    }
    {
      additionalWriters = [
        {
          primitive = "ownLeaves";
          pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
          target = "$HOME/.config/kimchi/harness/settings.json";
          writerAttr = [
            "home"
            "activation"
            "kimchiHarnessSettingsMerge"
          ];
        }
      ];
      ecosystem = "kimchi";
      mode = "hm";
      primitive = "ownLeaves";
      pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "settings";
      target = "$HOME/.config/kimchi/config.json";
      writerAttr = [
        "home"
        "activation"
        "kimchiConfigMerge"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "devenv";
      primitive = "ownLeaves";
      pruneTrigger = "On shell entry, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "settings";
      target = "$DEVENV_ROOT/.kiro/settings/cli.json";
      writerAttr = [
        "tasks"
        "ai:kiro:settings-merge"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownLeaves";
      pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
      surface = "settings";
      target = "$HOME/.kiro/settings/cli.json";
      writerAttr = [
        "home"
        "activation"
        "kiroSettingsMerge"
      ];
    }
    {
      ecosystem = "claude";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "skills";
      target = "$DEVENV_ROOT/.claude/skills/<name>/<leaf>";
      writerAttr = [
        "files"
        ".claude/skills/probe/SKILL.md"
      ];
    }
    {
      ecosystem = "codex";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "skills";
      target = "$DEVENV_ROOT/.agents/skills/<name>";
      writerAttr = [
        "files"
        ".agents/skills/probe"
      ];
    }
    {
      ecosystem = "codex";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "skills";
      target = "$HOME/.agents/skills/<name>";
      writerAttr = [
        "home"
        "file"
        ".agents/skills/probe"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "skills";
      target = "$DEVENV_ROOT/.github/skills/<name>/<leaf>";
      writerAttr = [
        "files"
        ".github/skills/probe/SKILL.md"
      ];
    }
    {
      ecosystem = "copilot";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "skills";
      target = "$HOME/.copilot/skills/<name>";
      writerAttr = [
        "home"
        "file"
        ".copilot/skills/probe"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "skills";
      target = "$DEVENV_ROOT/.kimchi/skills/<name>/<leaf>";
      writerAttr = [
        "files"
        ".kimchi/skills/probe/SKILL.md"
      ];
    }
    {
      ecosystem = "kimchi";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "skills";
      target = "$HOME/.config/kimchi/harness/skills/<name>";
      writerAttr = [
        "home"
        "file"
        ".config/kimchi/harness/skills/probe"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "devenv";
      primitive = "ownPathDeclarative";
      pruneTrigger = "devenv:files:cleanup on SHELL ENTRY ONLY removes retired store symlinks; retained entries are regenerated. Real files are not pruned.";
      surface = "skills";
      target = "$DEVENV_ROOT/.kiro/skills/<name>/<leaf>";
      writerAttr = [
        "files"
        ".kiro/skills/probe/SKILL.md"
      ];
    }
    {
      ecosystem = "kiro";
      mode = "hm";
      primitive = "ownPathDeclarative";
      pruneTrigger = "Home Manager generation diff on switch; changed declarations replace the store symlink.";
      surface = "skills";
      target = "$HOME/.kiro/skills/<name>";
      writerAttr = [
        "home"
        "file"
        ".kiro/skills/probe"
      ];
    }
  ];
  supplements = {
    "settings/claude/hm" = [
      {
        primitive = "ownLeaves";
        pruneTrigger = "On activation, lib/ai/own.nix's write entry runs lib/ai/own.py, which reads the leaves the prior generation's ledger recorded, removes the retired ones, reasserts the declared ones, and preserves unowned siblings. Both loops live in that program's `run`: every retraction across every target, then every assertion.";
        target = "$HOME/.claude.json";
        writerAttr = [
          "home"
          "activation"
          "claudeUnpinLaunchEffort"
        ];
      }
    ];
  };
}
