# config/generate-devenv-yaml.nix — generate devenv.yaml from flake.nix + flake.lock.
#
# Single source of truth: flake.nix inputs. Revs pinned from flake.lock.
# devenv manages its own lock — we just constrain what it locks to.
#
# Usage: nix eval --raw --impure --expr 'import ./config/generate-devenv-yaml.nix {}'
{flakeLock ? builtins.fromJSON (builtins.readFile ../flake.lock)}: let
  inherit (flakeLock) nodes;
  rootInputs = nodes.root.inputs;

  mkInputEntry = name: let
    nodeName = rootInputs.${name};
    node = nodes.${nodeName};
    locked = node.locked or {};
    original = node.original or {};

    url =
      original.url
      or (
        if locked.type == "github"
        then "github:${locked.owner}/${locked.repo}"
        else if locked.type == "git"
        then locked.url
        else "unknown"
      );

    rev = locked.rev or null;

    inputFollows = node.inputs or {};
    followsNixpkgs = (inputFollows.nixpkgs or null) == ["nixpkgs"];
    # devenv uses upstream cache — no follows
    noFollows = name == "devenv";
  in {
    inherit name url rev;
    follows = followsNixpkgs && !noFollows;
  };

  inputEntries = map mkInputEntry (builtins.attrNames rootInputs);

  mkYamlEntry = entry: let
    urlWithRev =
      if entry.rev != null
      then "${entry.url}/${entry.rev}"
      else entry.url;
    followsBlock =
      if entry.follows
      then "\n    inputs:\n      nixpkgs:\n        follows: nixpkgs"
      else "";
  in "  ${entry.name}:\n    url: ${urlWithRev}${followsBlock}";

  yaml = builtins.concatStringsSep "\n" (
    [
      "# Generated by config/generate-devenv-yaml.nix — do not edit manually."
      "# Source of truth: flake.nix inputs + flake.lock revs."
      "# Regenerate: devenv tasks run generate:devenv-yaml"
      "allowUnfree: true"
      ""
      "inputs:"
    ]
    ++ map mkYamlEntry inputEntries
    ++ [""]
  );
in
  yaml
