#!/usr/bin/env python3
# cspell:ignore pstats sdoc tottime cumtime
"""bench-export -- what an export of this corpus costs, with source linking on
and off.

WHAT THE NUMBERS MEAN. One number is the wall time of ONE
`strictdoc export --formats=json` over the whole repository, measured around a
subprocess with `time.perf_counter`. Four arms, because two independent things
move the figure:

* on / off -- whether `REQUIREMENT_TO_SOURCE_TRACEABILITY` is in
  `project_features`. ON is the repository's own `strictdoc_config.py`
  unmodified; OFF is that same config with exactly that one feature dropped.
  Everything else -- the glob manifest, the excluded paths, the format stack --
  is shared, so the delta is the feature and nothing else.
* cold / warm -- whether strictdoc's pickle parse cache is populated. COLD
  wipes the arm's cache and output directories first; WARM is the next run
  against the cache the cold one left. Both are real states: a fresh worktree
  or a `.sdoc` edit storm is cold, an ordinary repeat export is warm.

The standing cost is the WARM delta. The cold delta is a first-run cost, paid
again whenever the cache is discarded.

The measurements this reproduces, their interpretation and the caveats are
EV-STRICTDOC-EXPORT-TIMING (docs/plans/shared-understanding/). Numbers move with
the corpus, the machine and the strictdoc version; that node records which ones
its table was taken on. Re-run rather than trusting a number.

WHY THE ARMS ARE INTERLEAVED. A machine under a changing load makes "all the ON
runs, then all the OFF runs" attribute a drift in the load to the feature. Each
repetition runs on-cold, off-cold, on-warm, off-warm, so a drift lands on both
arms of a comparison rather than on one.

WHY EACH ARM KEEPS ITS OWN OUTPUT DIRECTORY, AND WHY THAT IS NOT TIDINESS.
strictdoc's pickle cache filename is an md5 of `output_dir + source path`
(strictdoc/backend/sdoc/pickle_cache.py, `get_cached_file_path`), so a fresh
`--output-dir` per run silently defeats the cache and turns every run into a
cold one. The arms therefore reuse one output directory each, and COLD is
expressed by deleting it rather than by moving it.

`--profile` ADDS A FIFTH, SERIALIZED RUN and is not part of the table. It is
one on-cold export under cProfile with `--no-parallelization`, because
strictdoc farms the per-file reads out to a process pool and a profiled parent
otherwise records 79% of its time inside multiprocessing queue plumbing. Read
its shares; its wall time is a serialized run's and belongs to no arm above.

NOTHING IS WRITTEN INTO THE REPOSITORY. The one derived config, both caches and
both output trees live under a scratch root (`$TMPDIR` by default, `--scratch`
to place it); the repository is read as an input path only.

THE DERIVED CONFIGS IMPORT THE REPOSITORY'S OWN `create_config()` AND MUTATE
WHAT IT RETURNS, rather than restating its keys. A copy would be a second thing
obliged to agree with `strictdoc_config.py` about the format stack, the excluded
paths and the grammar alias, and it would go stale silently -- the benchmark
would keep reporting a number for a configuration the repository no longer has.

RUN IT AS: `devenv tasks run strictdoc:bench`, or directly with the interpreter
that carries strictdoc, the way every other script here is run:

    strictdoc-grammar-extract dev/scripts/bench-export.py --runs 1 --profile
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Optional

#: The one feature this benchmark flips. Named here rather than imported: it is
#: a strictdoc vocabulary word, and the OFF arm has to be able to drop it from
#: whatever the repository config happens to enable.
TRACEABILITY_FEATURE = "REQUIREMENT_TO_SOURCE_TRACEABILITY"

#: The marker that says a config is this benchmark's and may be overwritten.
CONFIG_BASENAME = "bench_config.py"

#: strictdoc's own progress line for the source-file pass, which is the only
#: place the INDEXED file count is reported. Absent from an OFF run by
#: construction -- that pass is what the feature turns on.
INDEXED_COUNT = re.compile(r"^Reading source:\s+(\d+)\s+tasks", re.MULTILINE)

#: The derived config, written into the scratch root. It is a pure function of
#: three environment variables so that ONE file serves both arms: a second file
#: would be a second thing obliged to agree about how the repository config is
#: imported. strictdoc loads a `.py` config through `spec_from_file_location`
#: and does NOT put its directory on `sys.path`, so a shared helper module
#: beside it would not be importable -- hence env vars rather than an import.
CONFIG_TEMPLATE = '''\
"""GENERATED by dev/scripts/bench-export.py. Do not edit -- rewritten per run.

The repository's own `create_config()`, with the parse cache pointed at a
scratch directory and, in the OFF arm, `{feature}` dropped from
`project_features`. Read from the environment rather than baked in, so both
arms share one file.
"""

import importlib.util
import os
import sys
from pathlib import Path

FEATURE = "{feature}"
REPO_ROOT = Path(os.environ["SDOC_BENCH_REPO_ROOT"])


def _repo_config_module():
    """The repository's `strictdoc_config.py`, imported by path."""
    spec = importlib.util.spec_from_file_location(
        "sdoc_bench_repo_config", REPO_ROOT / "strictdoc_config.py"
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def create_config():
    config = _repo_config_module().create_config()
    # Set AFTER construction on purpose: the "$TMPDIR" sentinel the repository
    # config writes is expanded inside ProjectConfig.__init__, so an absolute
    # path assigned here is the final answer and is not re-expanded.
    config.dir_for_sdoc_cache = os.environ["SDOC_BENCH_CACHE_DIR"]
    if os.environ["SDOC_BENCH_FEATURE"] == "off":
        # Filtered rather than emptied: the repository may enable other
        # features later, and this benchmark flips exactly one of them.
        config.project_features = [
            feature
            for feature in config.project_features
            if str(getattr(feature, "value", feature)) != FEATURE
        ]
    return config
'''

#: Run strictdoc under cProfile in a child process. Written as `-c` source
#: rather than a scratch file so the profile arm needs no second artifact.
PROFILE_SHIM = """\
import cProfile
import sys

from strictdoc.cli.main import main

profile_out = sys.argv[-1]
sys.argv = ["strictdoc", *sys.argv[1:-1]]

profiler = cProfile.Profile()
profiler.enable()
try:
    main()
except SystemExit:
    pass
finally:
    profiler.disable()
    profiler.dump_stats(profile_out)
"""

#: Which part of the run a profiled frame belongs to. FIRST MATCH WINS, so the
#: narrow buckets are listed above the broad one: `backend/sdoc_source_code`
#: would otherwise be swallowed by the `backend/sdoc` prefix, which is a
#: different thing entirely (the `.sdoc` document parser).
PROFILE_BUCKETS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "walk",
        (
            "file_tree.py",
            "path_filter.py",
            "source_files_finder.py",
            "posixpath.py",
            "/os.py",
        ),
    ),
    (
        "source read",
        (
            "sdoc_source_code",
            "sdoc_extractors",
            "reader_registry.py",
            "caching_reader.py",
            "file_traceability_index.py",
            "tree_sitter",
            "marker_parser.py",
            "marker_lexer.py",
            # strictdoc parses `@relation(...)` markers with Lark, and
            # deserializing that grammar is a real slice of a cold run.
            "lark",
        ),
    ),
    (
        "sdoc parse",
        (
            "backend/sdoc/",
            "backend/json/",
            "pickle_cache.py",
            "textx",
            "arpeggio",
            "helpers/md5.py",
            "_pickle",
        ),
    ),
)


class BenchError(Exception):
    """Anything that makes a measurement impossible or meaningless."""


# ── locating things ──────────────────────────────────────────────────────


def find_repo_root(start: Path) -> Path:
    """The repository root, found the way every scribe program finds it.

    By walking up for `strictdoc_config.py`: there is exactly one, at the root,
    which is what puts every document in one graph.
    """
    current = start.resolve()
    while True:
        if (current / "strictdoc_config.py").is_file():
            return current
        if current.parent == current:
            raise BenchError(
                f"no strictdoc_config.py in {start} or any parent -- run "
                "inside the repository, or pass --repo-root"
            )
        current = current.parent


def strictdoc_command() -> list[str]:
    """How to invoke strictdoc, preferring the binary on PATH.

    The fallback matters when this runs outside a dev shell: `sys.executable`
    is strictdoc's own venv interpreter whenever this script is launched
    through `strictdoc-grammar-extract`, so the package is importable even
    when no wrapper is on PATH.
    """
    binary = shutil.which("strictdoc")
    if binary is not None:
        return [binary]
    try:
        import strictdoc  # noqa: F401
    except ImportError as error:
        raise BenchError(
            "no `strictdoc` on PATH and the strictdoc package is not "
            f"importable ({error}) -- run this through "
            "`strictdoc-grammar-extract`, or inside `devenv shell`"
        ) from error
    return [sys.executable, "-c", "from strictdoc.cli.main import main; main()"]


def default_scratch_root(repo_root: Path) -> Path:
    """A stable per-repository scratch root under `$TMPDIR`.

    Stable rather than a fresh `mkdtemp`, for two reasons that pull the same
    way: the cache key embeds the output directory, so a moving scratch root
    would make every warm arm secretly cold; and a fresh directory per
    invocation accumulates a full export tree each time.
    """
    digest = hashlib.md5(str(repo_root).encode("utf-8")).hexdigest()[:12]
    return Path(tempfile.gettempdir()) / "strictdoc-bench" / digest


# ── one export ───────────────────────────────────────────────────────────


class Arm:
    """One (feature, cache, output) triple, and the runs measured against it."""

    def __init__(self, name: str, feature: str, scratch: Path) -> None:
        self.name = name
        self.feature = feature
        self.cache_dir = scratch / f"cache-{feature}"
        self.output_dir = scratch / f"out-{feature}"

    def wipe(self) -> None:
        for directory in (self.cache_dir, self.output_dir):
            shutil.rmtree(directory, ignore_errors=True)


def run_export(
    command: list[str],
    *,
    arm: Arm,
    repo_root: Path,
    config_path: Path,
    scratch: Path,
    profile_out: Optional[Path] = None,
) -> tuple[float, subprocess.CompletedProcess]:
    """One export. Returns its wall time and the finished process."""
    arm.cache_dir.mkdir(parents=True, exist_ok=True)
    arm.output_dir.mkdir(parents=True, exist_ok=True)

    environment = dict(os.environ)
    environment["SDOC_BENCH_REPO_ROOT"] = str(repo_root)
    environment["SDOC_BENCH_CACHE_DIR"] = str(arm.cache_dir)
    environment["SDOC_BENCH_FEATURE"] = arm.feature
    # STRICTDOC_CACHE_DIR is read BEFORE dir_for_sdoc_cache and asserts it
    # equals exactly "Output/_cache", so a caller who has it set would abort
    # every arm. Dropped rather than honoured: it is not a relocation lever.
    environment.pop("STRICTDOC_CACHE_DIR", None)

    arguments = [
        "export",
        str(repo_root),
        "--config",
        str(config_path),
        "--output-dir",
        str(arm.output_dir),
        "--formats=json",
    ]
    if profile_out is not None:
        # `--no-parallelization` is what makes the profile READABLE rather than
        # a wall of `threading.join`. strictdoc farms the per-file reads out to
        # a process pool, so a profiled parent records the wait and none of the
        # work: measured, 79% of a parallel profile lands in multiprocessing
        # queue plumbing. The cost is that this run's WALL TIME is not
        # comparable with the timed arms above; only its shape is.
        argv = [
            sys.executable,
            "-c",
            PROFILE_SHIM,
            *arguments,
            "--no-parallelization",
            str(profile_out),
        ]
    else:
        argv = [*command, *arguments]

    started = time.perf_counter()
    finished = subprocess.run(  # noqa: S603
        argv,
        cwd=str(scratch),
        env=environment,
        capture_output=True,
        text=True,
        check=False,
    )
    elapsed = time.perf_counter() - started
    return elapsed, finished


def fail_on_export_error(arm_label: str, finished: subprocess.CompletedProcess) -> None:
    if finished.returncode == 0:
        return
    output = (finished.stdout or "") + (finished.stderr or "")
    tail = "\n".join(output.splitlines()[-25:])
    raise BenchError(
        f"{arm_label}: strictdoc export exited {finished.returncode}\n{tail}"
    )


# ── the profile arm ──────────────────────────────────────────────────────


def report_profile(profile_out: Path) -> None:
    """Top frames by cumulative time, then the same frames bucketed."""
    import pstats

    statistics = pstats.Stats(str(profile_out))
    print()
    print(
        "### profile of one on-cold export, `--no-parallelization` "
        "(top 15 by cumulative time)"
    )
    print()
    statistics.sort_stats("cumulative").print_stats(15)

    totals: dict[str, float] = {}
    for (filename, _lineno, name), entry in statistics.stats.items():  # type: ignore[attr-defined]
        bucket = bucket_of(filename, name)
        totals[bucket] = totals.get(bucket, 0.0) + entry[2]

    grand_total = sum(totals.values())
    print("### the same run, bucketed by own (not cumulative) time")
    print()
    print("| bucket | own time (s) | share |")
    print("| --- | ---: | ---: |")
    for bucket, seconds in sorted(totals.items(), key=lambda item: -item[1]):
        share = (100.0 * seconds / grand_total) if grand_total else 0.0
        print(f"| {bucket} | {seconds:.3f} | {share:.1f}% |")
    print(f"| **total** | **{grand_total:.3f}** | |")
    print()
    print(
        "This run is single-process by construction, so the total is the "
        "whole run -- but a serialized one, and slower than the timed arms."
    )


def bucket_of(filename: str, function: str) -> str:
    """Which bucket a profiled frame belongs to.

    The FUNCTION NAME is matched as well as the filename, because a C
    extension's frames carry the filename `~` -- `tree_sitter.Parser.parse` is
    charged to "other" on a filename match alone, which is precisely the work
    the "source read" bucket exists to count.
    """
    subject = f"{filename}:{function}"
    for bucket, needles in PROFILE_BUCKETS:
        for needle in needles:
            if needle in subject:
                return bucket
    return "other"


# ── the table ────────────────────────────────────────────────────────────


def print_table(results: dict[str, list[float]], runs: int) -> None:
    headers = ["arm", *(f"run{index + 1}" for index in range(runs)), "mean"]
    print()
    print("| " + " | ".join(headers) + " |")
    print("| --- " + "| ---: " * (runs + 1) + "|")
    for arm_label, timings in results.items():
        mean = sum(timings) / len(timings) if timings else 0.0
        cells = [f"{value:.2f} s" for value in timings]
        cells += [""] * (runs - len(cells))
        print(f"| {arm_label} | " + " | ".join(cells) + f" | {mean:.2f} s |")


def print_deltas(results: dict[str, list[float]]) -> None:
    def mean(label: str) -> Optional[float]:
        timings = results.get(label) or []
        return sum(timings) / len(timings) if timings else None

    print()
    for state in ("cold", "warm"):
        on_mean = mean(f"on-{state}")
        off_mean = mean(f"off-{state}")
        if on_mean is None or off_mean is None:
            continue
        delta = on_mean - off_mean
        share = (100.0 * delta / off_mean) if off_mean else 0.0
        print(
            f"{state}: source linking costs +{delta:.2f} s "
            f"({share:+.0f}% against {off_mean:.2f} s with it off)"
        )


# ── main ─────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="bench-export",
        description=(
            "Wall time of a JSON export of this corpus, with source linking "
            "on and off, cold and warm. See EV-STRICTDOC-EXPORT-TIMING."
        ),
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="the repository to export; found by walking up for "
        "strictdoc_config.py when omitted",
    )
    parser.add_argument(
        "--runs",
        type=int,
        default=int(os.environ.get("SDOC_BENCH_RUNS", "2")),
        help="repetitions of the interleaved four-arm block (default 2, or "
        "$SDOC_BENCH_RUNS)",
    )
    parser.add_argument(
        "--scratch",
        type=Path,
        default=None,
        help="where the derived configs, caches and export trees go; a "
        "stable per-repository directory under $TMPDIR when omitted",
    )
    parser.add_argument(
        "--profile",
        action="store_true",
        default=os.environ.get("SDOC_BENCH_PROFILE", "") not in ("", "0"),
        help="additionally run one on-cold export under cProfile, serialized, "
        "and report where the time went (or set $SDOC_BENCH_PROFILE=1)",
    )
    arguments = parser.parse_args()

    if arguments.runs < 1:
        print("bench-export: --runs must be at least 1", file=sys.stderr)
        return 2

    try:
        repo_root = (
            arguments.repo_root.resolve()
            if arguments.repo_root is not None
            else find_repo_root(Path.cwd())
        )
        scratch = (
            arguments.scratch.resolve()
            if arguments.scratch is not None
            else default_scratch_root(repo_root)
        )
        if scratch.is_relative_to(repo_root):
            raise BenchError(
                f"--scratch {scratch} is inside the repository; this "
                "benchmark never writes into the tree it measures"
            )
        scratch.mkdir(parents=True, exist_ok=True)
        config_path = scratch / CONFIG_BASENAME
        config_path.write_text(
            CONFIG_TEMPLATE.format(feature=TRACEABILITY_FEATURE),
            encoding="utf-8",
        )

        command = strictdoc_command()
        version = subprocess.run(  # noqa: S603
            [*command, "--version"],
            capture_output=True,
            text=True,
            check=False,
        ).stdout.strip()

        arms = {"on": Arm("on", "on", scratch), "off": Arm("off", "off", scratch)}
        results: dict[str, list[float]] = {
            "on-cold": [],
            "off-cold": [],
            "on-warm": [],
            "off-warm": [],
        }
        indexed: Optional[int] = None

        for repetition in range(arguments.runs):
            # Interleaved: both colds, then both warms, so a drift in machine
            # load lands on both sides of each comparison.
            for label, feature, cold in (
                ("on-cold", "on", True),
                ("off-cold", "off", True),
                ("on-warm", "on", False),
                ("off-warm", "off", False),
            ):
                arm = arms[feature]
                if cold:
                    arm.wipe()
                print(
                    f"[{repetition + 1}/{arguments.runs}] {label} ...",
                    end=" ",
                    flush=True,
                    file=sys.stderr,
                )
                elapsed, finished = run_export(
                    command,
                    arm=arm,
                    repo_root=repo_root,
                    config_path=config_path,
                    scratch=scratch,
                )
                fail_on_export_error(label, finished)
                print(f"{elapsed:.2f} s", file=sys.stderr)
                results[label].append(elapsed)
                if indexed is None and feature == "on":
                    match = INDEXED_COUNT.search(
                        (finished.stdout or "") + (finished.stderr or "")
                    )
                    if match is not None:
                        indexed = int(match.group(1))

        print(f"# strictdoc export timing -- {repo_root}")
        print()
        print(f"- strictdoc: {version or 'unknown'}")
        print(
            "- indexed source files: "
            + (str(indexed) if indexed is not None else "not reported")
        )
        print(f"- repetitions: {arguments.runs}")
        print(f"- scratch root: {scratch}")
        print_table(results, arguments.runs)
        print_deltas(results)

        if arguments.profile:
            profile_out = scratch / "on-cold.pstats"
            arm = arms["on"]
            arm.wipe()
            print("[profile] on-cold under cProfile ...", file=sys.stderr)
            _, finished = run_export(
                command,
                arm=arm,
                repo_root=repo_root,
                config_path=config_path,
                scratch=scratch,
                profile_out=profile_out,
            )
            fail_on_export_error("profile on-cold", finished)
            report_profile(profile_out)
    except BenchError as error:
        print(f"bench-export: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
