#!/usr/bin/env bash
# lab-up.sh — materialize an agent-primitive lab's fake user-global.
# See docs/plans/agent-primitive-labs-design.md.
#
# USER-RUN. Builds this repo's `homeConfigurations.lab-<name>.config.home-files`
# flake output into a writable clean-room fake user-global at
# /var/tmp/nat-labs/<name>/home/, replays the home-manager activation-only
# writes (launch-effort unpin + copilot/kiro settings merges) that never
# appear in home-files, seeds the Claude trust gate, and writes an .envrc
# into <name>/work/ exporting the isolation contract. It never touches your
# real ~/.claude or ~/.kiro config.
#
# Labs materialize OUTSIDE $HOME. This is load-bearing: Claude walks every
# ancestor directory for CLAUDE.md up to and including /home, so a lab under
# $HOME silently inherits ~/.claude/CLAUDE.md regardless of CLAUDE_CONFIG_DIR.
#
# Usage: dev/scripts/lab-up.sh [--reset] <name>
#   --reset wipes /var/tmp/nat-labs/<name> before rematerializing. Without
#   it, re-running is additive: cp -rL never deletes, so files removed from
#   labs/<name>/lab.nix since the last run would otherwise linger.
set -euETo pipefail
shopt -s inherit_errexit 2>/dev/null || :

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd -- "${script_dir}/../.." && pwd)"
lab_root="/var/tmp/nat-labs"

log() { echo "==> $*" >&2; }

reset=0
if [ "${1:-}" = "--reset" ]; then
  reset=1
  shift
fi

name="${1:-}"
if [ -z "$name" ]; then
  log "usage: dev/scripts/lab-up.sh [--reset] <name>"
  log "defined labs:"
  ls -1 "${root}/labs" >&2
  exit 2
fi
case "$name" in
*/* | *..*)
  log "invalid lab name: '$name' (must not contain / or ..)"
  exit 2
  ;;
esac
if [ ! -f "${root}/labs/${name}/lab.nix" ]; then
  log "no such lab: $name (expected labs/$name/lab.nix)"
  exit 2
fi

lab="${lab_root}/${name}"

if [ "$reset" -eq 1 ] && [ -d "$lab" ]; then
  log "resetting $lab"
  # u+w first: the copied tree includes dereferenced, still-read-only
  # Nix store files/dirs that rm -rf can't otherwise remove.
  chmod -R u+w "$lab"
  rm -rf "$lab"
fi

log "building fake user-global for '$name'"
hf=$(nix build "${root}#homeConfigurations.lab-${name}.config.home-files" \
  --max-jobs 1 --no-link --print-out-paths)

log "materializing $lab"
mkdir -p "$lab/home" "$lab/work"

# -L dereferences store symlinks so the copy is self-contained and
# writable. chmod -R u+w AFTER the copy: --no-preserve=mode would strip
# the exec bit off .claude/hooks/*.
cp -rL "$hf/." "$lab/home/"
chmod -R u+w "$lab/home"

# Replay activation-only writes. These jq merges never appear in
# home-files. They are $HOME-parameterized and reference absolute store
# paths, so they run standalone with HOME repointed.
for entry in claudeUnpinLaunchEffort copilotSettingsMerge kiroSettingsMerge; do
  eval_err="$(mktemp)"
  if body=$(nix eval --raw \
    "${root}#homeConfigurations.lab-${name}.config.home.activation.${entry}.data" \
    2>"$eval_err"); then
    rm -f "$eval_err"
  elif grep -qE 'does not provide attribute|does not exist|missing attribute' "$eval_err"; then
    # Genuinely absent — entries are only emitted when the relevant app
    # is enabled. Expected and fine, unlike any other eval failure below.
    log "activation '$entry' not present — skipping"
    rm -f "$eval_err"
    continue
  else
    log "nix eval failed for activation '$entry':"
    cat "$eval_err" >&2
    rm -f "$eval_err"
    exit 1
  fi

  log "replaying activation '$entry'"
  # Stubs for the home-manager activation harness helpers that the
  # snippets may reference outside a real activation run.
  HOME="$lab/home" bash -c "
    set -euETo pipefail
    shopt -s inherit_errexit 2>/dev/null || :
    _iNote() { :; }
    _iWarn() { :; }
    run() { \"\$@\"; }
    VERBOSE_ARG=\"\"
    DRY_RUN_CMD=\"\"
    $body
  "
done

# Seed the trust gate. Without hasTrustDialogAccepted, Claude Code treats
# the freshly materialized $lab/home/.claude as an untrusted directory and
# won't honor its settings.json.
cj="$lab/home/.claude.json"
[ -f "$cj" ] || echo '{}' >"$cj"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
jq '.hasTrustDialogAccepted = true' "$cj" >"$tmp"
mv "$tmp" "$cj"
trap - EXIT

log "writing $lab/work/.envrc"
cat >"$lab/work/.envrc" <<ENVRC
#!/usr/bin/env bash
# Generated by 'dev/scripts/lab-up.sh $name'. Do not edit; regenerate
# instead. Source of truth: labs/$name/lab.nix.
set -euETo pipefail
shopt -s inherit_errexit 2>/dev/null || :

# Clean-room user scope. HOME and XDG_DATA_HOME are deliberately NOT set:
# both relocate Kiro's auth DB and destroy session state.
export CLAUDE_CONFIG_DIR="$lab/home/.claude"
export KIRO_HOME="$lab/home/.kiro"
# Set-but-empty pins credentials and the keychain service name back to
# the real ~/.claude, so auth survives the config redirect.
export CLAUDE_SECURESTORAGE_CONFIG_DIR=""
export NAT_LAB="$name"
export NAT_LAB_REPO="$root"
ENVRC

log "lab '$name' ready:"
echo "$lab/work"
