# markdownlint-cli2 — re-pinned onto this repo's update cadence.
#
# Carried for CADENCE, not for a version delta. At absorption this sat at
# exact parity with nixpkgs and with npm (both 0.23.2) and was absorbed
# anyway — see "Absorption is about CADENCE" in
# dev/fragments/overlays/overlay-pattern.md. Parity today says nothing
# about how long the NEXT release takes to reach a channel, which is the
# only quantity absorption buys down.
#
# `.override`, NOT `overrideAttrs`, and that is not a style choice.
# `buildNpmPackage` is a `lib.extendMkDerivation` whose `extendDrvArgs`
# computes `npmDeps = fetchNpmDeps { hash = npmDepsHash; ... }` from the
# INCOMING args, so an `npmDepsHash` injected through `overrideAttrs`
# composes on the OUTPUT and is inert — it would build the new source
# against the old dependency set with no error at all. Measured on bruno;
# overlays/generic/bruno.nix carries the numbers.
#
# WHY THE VERSION AND HASHES ARE INLINE, not in a `-sources.json`
# sidecar. Upstream ships NO package-lock.json, so nixpkgs generates one
# and vendors it beside the package; the build symlinks it in via
# `postPatch`. A bump therefore has to regenerate that lockfile, which is
# `nix-update --generate-lockfile` — and nix-update rewrites the `.nix`
# in place rather than a sidecar. So this package uses the `file` +
# `flags` row shape in config/update-targets.nix (like agnix), not the
# `--use-update-script` + sidecar shape the fetchzip packages use.
#
# The lockfile beside this file is OURS, regenerated by that flag. It is
# a GENERATED artifact: do not hand-edit it, and do not assume it matches
# nixpkgs' copy after the first bump.
#
# WHAT IT IS FOR HERE. This is the BACKUP half of the markdown
# table-cell-count gate in `config/repo-validation.nix`; rumdl is the
# primary. They share the rule number MD056 and catch DISJOINT halves of
# it — markdownlint catches an over-wide body row (the cause), rumdl
# catches a header/delimiter disagreement (the break) and markdownlint
# cannot, because once the counts disagree its parser stops seeing a
# table at all. Measured: rumdl 0.04s over this corpus, markdownlint
# 8.2s, which is why the Rust one leads. Neither is redundant; that
# config's header carries the table.
#
# Free (MIT). ensureUnfreeCheck in default.nix passes free packages
# through unwrapped.
{
  inputs,
  final,
  ...
}: let
  # Cache-hit parity: every build input comes from THIS repo's nixpkgs
  # pin, never the consumer's `final`. `final.stdenv.hostPlatform.system`
  # is the only thing read from the consumer — see
  # dev/fragments/overlays/overlay-pattern.md.
  ourPkgs = import inputs.nixpkgs {
    inherit (final.stdenv.hostPlatform) system;
  };
  inherit (ourPkgs) lib;

  # Bumped in place by `nix-update --generate-lockfile` (see the
  # config/update-targets.nix row). Keep the literals on their own lines:
  # nix-update rewrites them by pattern.
  version = "0.23.2";
  srcHash = "sha256-nWKkQdzwm+jLoZYs25USsdbRwXj++aS1tif2ro4FsBI=";
  npmDepsHash = "sha256-cUwSR+B1MA6wciAemCxevT1VrtSEGzPUpBKzZzMul2E=";
in
  ourPkgs.markdownlint-cli2.override (_: {
    buildNpmPackage = args:
      ourPkgs.buildNpmPackage (finalAttrs: let
        upstream = (lib.toFunction args) finalAttrs;
      in
        upstream
        // {
          inherit version npmDepsHash;

          # Re-POINTED, not restated: `pkgs.markdownlint-cli2.src` is
          # `fetchFromGitHub`'s own `lib.makeOverridable`, so overriding
          # `tag` + `hash` keeps `owner` and `repo`. nixpkgs passes `tag`
          # (the fetcher asserts exactly one of `rev`/`tag`), so only
          # `tag` moves.
          src = upstream.src.override {
            tag = "v${version}";
            hash = srcHash;
          };

          # OURS, not nixpkgs'. Upstream ships no lockfile, so the build
          # symlinks a vendored one in; inheriting nixpkgs' would pin our
          # dependency set to whatever version THEY carry the moment our
          # version leads theirs. `postPatch` is also an input to
          # `npmDepsHash`, so the two move together or not at all.
          postPatch = ''
            rm -f .npmrc
            ln -s ${./markdownlint-cli2-package-lock.json} package-lock.json
          '';

          # nixpkgs' own `updateScript` would rewrite the NIXPKGS
          # expression, not ours. The sweep drives this package through
          # its config/update-targets.nix row instead.
          passthru =
            (upstream.passthru or {})
            // {updateScript = null;};
        });
  })
